-- MySQL Script generated by MySQL Workbench
-- Sex 24 Mar 2017 14:34:55 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sghq
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sghq
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sghq` DEFAULT CHARACTER SET utf8 ;
USE `sghq` ;

-- -----------------------------------------------------
-- Table `sghq`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sghq`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sghq`.`titulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sghq`.`titulo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`id`, `idCategoria`),
  INDEX `fk_titulo_categoria1_idx` (`idCategoria` ASC),
  CONSTRAINT `fk_titulo_categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `sghq`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sghq`.`subtitulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sghq`.`subtitulo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `idTitulo` INT NOT NULL,
  PRIMARY KEY (`id`, `idTitulo`),
  INDEX `fk_subtitulo_titulo_idx` (`idTitulo` ASC),
  CONSTRAINT `fk_subtitulo_titulo`
    FOREIGN KEY (`idTitulo`)
    REFERENCES `sghq`.`titulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sghq`.`arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sghq`.`arquivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `idTitulo` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`id`, `idTitulo`, `idCategoria`),
  INDEX `fk_arquivo_titulo1_idx` (`idTitulo` ASC, `idCategoria` ASC),
  CONSTRAINT `fk_arquivo_titulo1`
    FOREIGN KEY (`idTitulo` , `idCategoria`)
    REFERENCES `sghq`.`titulo` (`id` , `idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
